spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:import.sql
    username: sa
    password: password
    url: jdbc:h2:mem:test
